# Generated by Django 4.2.7 on 2023-12-03 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateField()),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.cita')),
            ],
        ),
    ]
