# Generated by Django 4.2.7 on 2023-12-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamacion',
            name='estado',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=10),
        ),
    ]
