# Generated by Django 4.2.7 on 2023-12-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamacion',
            name='hora',
        ),
    ]
