# Generated by Django 4.2.7 on 2023-12-01 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamaciones', '0002_remove_reclamacion_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamacion',
            name='invitado',
        ),
        migrations.RemoveField(
            model_name='reclamacion',
            name='usuario',
        ),
    ]
