# Generated by Django 4.2.7 on 2023-11-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='especialidades',
            field=models.ManyToManyField(related_name='especialistas_relacionados', to='citas.servicio'),
        ),
    ]
