# Generated by Django 4.2.7 on 2023-12-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='agotado',
            field=models.BooleanField(default=False),
        ),
    ]
