# Generated by Django 4.2.7 on 2023-12-09 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_servicio_agotado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.especialista')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.servicio')),
            ],
        ),
    ]
