# Generated by Django 4.2.7 on 2023-11-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_especialista_especialidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='especialidades',
            field=models.ManyToManyField(related_name='especialistas', to='citas.servicio'),
        ),
    ]
