# Generated by Django 4.2.7 on 2023-11-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_especialista_especialidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(),
        ),
    ]
