# Generated by Django 4.2.7 on 2023-11-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_especialista_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialista',
            name='imagen',
        ),
    ]
