# Generated by Django 4.2.7 on 2023-11-19 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0009_remove_especialista_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.servicio')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.especialista')),
            ],
        ),
    ]
