# Generated by Django 4.2.7 on 2023-11-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0010_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
    ]
