# Generated by Django 4.2.7 on 2023-11-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citas", "0012_delete_apertura_delete_timeslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicio",
            name="precio",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
