# Generated by Django 4.2.7 on 2023-11-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0014_alter_servicio_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='contrarembolso',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
