# Generated by Django 4.2.7 on 2023-12-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0014_alter_servicio_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='especialistas'),
        ),
    ]
