# Generated by Django 4.2.7 on 2023-11-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0015_cita_contrarembolso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='pagado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
