# Generated by Django 4.2.7 on 2023-11-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0016_cita_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='precio.html',
            field=models.TextField(default=''),
        ),
    ]
