# Generated by Django 4.2.7 on 2023-11-28 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0017_alter_servicio_precio"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicio",
            old_name="precio.html",
            new_name="precioId",
        ),
        migrations.RemoveField(
            model_name="cita",
            name="contrarembolso",
        ),
    ]
