# Generated by Django 4.2.7 on 2023-11-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0018_rename_precio_servicio_precioid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cita",
            name="metodo_pago",
            field=models.CharField(
                choices=[("EF", "Efectivo"), ("TA", "Tarjeta")],
                default="EF",
                max_length=2,
            ),
        ),
    ]
