# Generated by Django 4.2.7 on 2023-11-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0019_cita_metodo_pago"),
    ]

    operations = [
        migrations.AddField(
            model_name="cita",
            name="check_pago",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
